# Generated by Django 4.2.6 on 2023-11-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_rename_district_case_fir_occuranced_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='victim_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.victiminfo'),
        ),
    ]
