# Generated by Django 4.2.6 on 2023-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_userprofile_victim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_fir',
            name='occurance_time',
            field=models.TimeField(null=True),
        ),
    ]
