# Generated by Django 4.2.6 on 2023-11-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_physicalstructure_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstructure',
            name='dis_guis_mark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicalstructure',
            name='dis_guis_mark_brief',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='height',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstructure',
            name='weight',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
