# Generated by Django 4.2.6 on 2023-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_physicalstructure_dis_guis_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_fir',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Going', 'On Going'), ('Completed', 'Completed')], default='Pending', max_length=255),
        ),
    ]
